### ISSUE TITLE
Add Modifier parameter to BottomSheetHost

### ISSUE THREAD

**Issue by sebastianmarschall** [hrach/navigation-compose-ext#32]
It would be great if you could add a `Modifier` parameter to `BottomSheetHost` and pass it through to `androidx.compose.material3.ModalBottomSheet`.

What do you think?

That being said, great library!

**Comment by hrach** [comment]
Makes sense! Feel free to create PR before I get to it :) Thx.

**Comment by hrach** [comment]
Closed by #33
