### ISSUE TITLE
BottomSheet: custom properties

### ISSUE THREAD

**Issue by DavidGrygar** [hrach/navigation-compose-ext#38]
Is it possible to add support for passing custom properties to ModalBottomSheet which is in BottomSheetHost?
Concretely:
- sheetMaxWidth
- shape
- containerColor
- contentColor
- tonalElevation
- scrimColor
- dragHandle

**Comment by hrach** [comment]
PR welcomed :)

**Comment by DavidGrygar** [comment]
Hmm I am now thinking if this is not sufficient replace without needs of your 3-rd party library:
```
dialog<Destinations.BottomSheet> {
    ModalBottomSheet(...)
}
```
What do you think about this solution?
PS: It is possible that it only works in compose-material3 version 1.3.0-beta

**Comment by hrach** [comment]
@DavidGrygar 

> Hmm I am now thinking if this is not sufficient replace without needs of your 3-rd party library

Depends on what you want and what you expect. For example, I would be very careful with predictive back handling here and insets (keyboard stuff). I haven't tested that though. Feel free to use it if it suits you. 

Marking our comments as offtopic, please open another issue if you want to discuss it more.

**Comment by mimai-hen** [comment]
Hi, I need these custom properties too. Tried to initiate a pull request, but I get permission error. It's the first time I do a pull request, so may be I'm doing something wrong (I did the updates in a new bottomsheet-custom-properties branch, but unable to push it to the remote) ... do I need specific rights ? Thanks for your help

```
12:00:10.208: [navigation-compose-ext] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/bottomsheet-custom-properties:refs/heads/bottomsheet-custom-properties --set-upstream
remote: Permission to hrach/navigation-compose-ext.git denied to mimai-hen.
fatal: unable to access 'https://github.com/hrach/navigation-compose-ext.git/': The requested URL returned error: 403
```

**Comment by hrach** [comment]
To push PR on Github, you have to fork and pullreqest from the fork's branch to main branch her. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo

**Comment by mimai-hen** [comment]
Thank you :-) PR done !
